from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
import os
import hashlib
import time
from backend.db import get_db_connection

router = APIRouter(prefix="/sync", tags=["sync"])

# Track recent unlinks for rename detection (path -> {hash, timestamp})
_recent_unlinks: dict = {}
RENAME_WINDOW_MS = 2000  # 2 second window to pair unlink+add as a rename

class FSEvent(BaseModel):
    event: str  # 'add', 'change', 'unlink'
    path: str

class FSEventResponse(BaseModel):
    status: str
    reason: str = ""
    action: str = ""
    conflict: bool = False
    note_id: str = ""


async def handleFileSystemEvent(event: str, path: str, dirty_note_ids: list, db) -> dict:
    """
    Handles file system events generated by Chokidar in the main process.
    
    Args:
        event: 'add', 'change', or 'unlink'
        path: absolute path to the .md file
        dirty_note_ids: list of note IDs currently being edited (have unsaved changes)
        db: database connection
    
    Returns dict with status, action, and optional conflict flag.
    """
    if not path.endswith('.md'):
        return {"status": "ignored", "reason": "Not a markdown file"}

    # --- UNLINK ---
    if event == 'unlink':
        async with db.execute("SELECT id, content_hash FROM notes WHERE file_path = ?", (path,)) as cursor:
            row = await cursor.fetchone()
            if row:
                # Store for rename detection
                _recent_unlinks[path] = {
                    "note_id": row["id"],
                    "content_hash": row["content_hash"],
                    "timestamp": time.time()
                }
                return {"status": "processed", "action": "unlink_tracked", "note_id": row["id"]}
        return {"status": "ignored", "reason": "No matching note in DB"}

    # --- ADD / CHANGE ---
    if not os.path.exists(path):
        return {"status": "ignored", "reason": "File does not exist on disk"}

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    current_hash = hashlib.sha256(content.encode('utf-8')).hexdigest()

    # Look up in DB by path
    async with db.execute("SELECT id, content_hash FROM notes WHERE file_path = ?", (path,)) as cursor:
        row = await cursor.fetchone()

    if row:
        # Known note
        if row["content_hash"] == current_hash:
            # Internal save — hash matches, skip
            return {"status": "ignored", "reason": "Internal save"}
        else:
            # External edit detected
            note_id = row["id"]
            if note_id in dirty_note_ids:
                # CONFLICT: note has unsaved changes AND file changed externally
                return {
                    "status": "conflict",
                    "action": "conflict_detected",
                    "conflict": True,
                    "note_id": note_id
                }
            else:
                # Silently apply external change
                await db.execute(
                    "UPDATE notes SET content = ?, content_hash = ?, updated_at = ? WHERE id = ?",
                    (content, current_hash, int(time.time()), note_id)
                )
                await db.commit()
                # TODO M9: Re-embed this note in background
                return {"status": "processed", "action": "external_edit_applied", "note_id": note_id}
    else:
        # Unknown file — check if it's a rename (matches a recent unlink by hash)
        now = time.time()
        matched_unlink_path = None
        for unlink_path, info in list(_recent_unlinks.items()):
            if now - info["timestamp"] > RENAME_WINDOW_MS / 1000:
                del _recent_unlinks[unlink_path]
                continue
            if info["content_hash"] == current_hash:
                matched_unlink_path = unlink_path
                break

        if matched_unlink_path:
            # Rename detected — update file_path on existing note
            info = _recent_unlinks.pop(matched_unlink_path)
            await db.execute(
                "UPDATE notes SET file_path = ?, updated_at = ? WHERE id = ?",
                (path, int(time.time()), info["note_id"])
            )
            await db.commit()
            return {"status": "processed", "action": "rename_detected", "note_id": info["note_id"]}
        else:
            # Truly new external file — create a note for it
            import uuid
            note_id = str(uuid.uuid4())
            title = os.path.splitext(os.path.basename(path))[0]
            now_ts = int(time.time())
            await db.execute(
                "INSERT INTO notes (id, title, content, folder, created_at, updated_at, file_path, content_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (note_id, title, content, "", now_ts, now_ts, path, current_hash)
            )
            await db.commit()
            # TODO M9: Embed this note in background
            return {"status": "processed", "action": "external_creation", "note_id": note_id}


async def db_dep():
    db = await get_db_connection()
    try:
        yield db
    finally:
        await db.close()


class FSEventRequest(BaseModel):
    event: str
    path: str
    dirty_note_ids: list = []


@router.post("/fs-event")
async def fs_event(payload: FSEventRequest, db=Depends(db_dep)):
    return await handleFileSystemEvent(payload.event, payload.path, payload.dirty_note_ids, db)
